name: Run Python Script

on:
  push:
    branches:
      - main  # Ubah ke branch yang sesuai

jobs:
  run_script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run script
      run: python your_untitled4(2).py  # Ganti 'your_script.py' dengan nama file Anda
